# Generated by Django 3.2.5 on 2021-07-14 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
        ('reservation', '0002_alter_reservation_tableid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tableid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reservation', to='table.table'),
        ),
    ]
